{
  "formatVersion": "1.1",
  "component": {
    "url": "../../georoutes/1.3.23-preview/georoutes-1.3.23-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "georoutes",
    "version": "1.3.23-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "georoutes-jvm-1.3.23-preview.jar",
          "url": "georoutes-jvm-1.3.23-preview.jar",
          "size": 2937421,
          "sha512": "fa9b34cb903d67e5310daf138d4196dd9e730e0e48e4e3775df116c89e9f6e6afbbcd3c107cf25cce2b12953cb9a30492c3f73de195434af341c56e499cb5d0c",
          "sha256": "520025654752b7df6d3ef3629e5af251cb2475c83c10d6474d31e9b6e4196603",
          "sha1": "0dd48763ea3967a691dbefa3c33fc0bff0a1ee39",
          "md5": "314257c146ca1a463f0905546e7306bf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-http",
          "version": {
            "requires": "1.3.23-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-json-protocols",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-protocol-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-default",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client-engine-default",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "identity-api",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-json",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-defaults",
          "version": {
            "requires": "1.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "georoutes-jvm-1.3.23-preview.jar",
          "url": "georoutes-jvm-1.3.23-preview.jar",
          "size": 2937421,
          "sha512": "fa9b34cb903d67e5310daf138d4196dd9e730e0e48e4e3775df116c89e9f6e6afbbcd3c107cf25cce2b12953cb9a30492c3f73de195434af341c56e499cb5d0c",
          "sha256": "520025654752b7df6d3ef3629e5af251cb2475c83c10d6474d31e9b6e4196603",
          "sha1": "0dd48763ea3967a691dbefa3c33fc0bff0a1ee39",
          "md5": "314257c146ca1a463f0905546e7306bf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "georoutes-jvm-1.3.23-preview-sources.jar",
          "url": "georoutes-jvm-1.3.23-preview-sources.jar",
          "size": 493661,
          "sha512": "aa6acb0f19701b50db23222e389c130b686560cfcf230b38b0f5d59f7d3f5a515d43c1c279e1eccb2664d4f62fa7534006e8737329c10f271e71169d8aeefc47",
          "sha256": "5204d6788ddaee34788f0e910f05d59c33231c5c91c62ae47ce5f3649e07d3e5",
          "sha1": "244aab03e402e9b4296ad254683976f3a6a0b297",
          "md5": "900f75457bf5c4a510966ee0a41bd523"
        }
      ]
    }
  ]
}
