name: Test Android App
on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, main ]
jobs:
  test-android:
    name: Test Android
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bundler
        run: |
          bundle config --local path ./vendor/bundle
          bundle config --local deployment true
          bundle install

      - name: Setup Config
        working-directory:
        run: |
          base64 -d <<< ${{ secrets.SECRETS }} > custom.properties

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Unit Tests
        run: |
          ./gradlew testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: app/build/reports/androidTests/connected/
          retention-days: 1
